### PR TITLE
Added File property to SortSearchDescriptor

### PR DESCRIPTION
**Pull request by nickelbob**
I installed the editorconfig extension but my formatting still seems messed up, sorry about that.

### CODE REVIEW

**Comment by nickelbob** [comment]
Well, that didn't go so well. I just signed the CLA so maybe that's not updated yet.

Not sure why the project isn't building. If anyone knows offhand please comment and I'll fix it as soon as possible.

Thanks!

**Comment by Mpdreamz** [comment]
Hey @nickelbob thanks for the PR!

The CLA checks git emails with the email you used to sign the CLA, I can see you've signed it though.

The travis build still has hiccups now that we moved to paket which sometimes returns an error code while restoring it seems, I restarted the travis build manually and it seems fine now.

**Comment by Mpdreamz** [comment]
Squashed your commits with my formatting fixes so your changes come through cleanly, thanks again for  the PR!

**Comment by nickelbob** [comment]
Nice! Thanks so much for your help Martijn and thanks for Elasticsearch.Net! We use it more and more everyday and it's such a great selling point for .NET shops to get into Elasticsearch.

Thanks again!

**Comment by Mpdreamz** [comment]
Glad to hear! Positive vibes much appreciated :smile:

**Pull request closed without merging**
